# _config.yml
title: "وظفني - المنصة الذكية للتوظيف العراقي"
description: "أول منصة توظيف ذكية في العراق"
baseurl: ""
url: "https://muntadher26.github.io/Quadrat"
lang: "ar"
rtl: true

# إعدادات GitHub Pages
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# إعدادات الموقع
theme: null
exclude:
  - README.md
  - nojekyll.sh
